### ISSUE TITLE
Mac Configuration Issues

### ISSUE THREAD

**Issue by pastorsj** [RedisLabsModules/rejson#4]
I was able to clone the repository, install cmake via brew, run the bootstrap.sh file and had no errors when doing so. However, when I explored the lib directory, instead of getting a `rejson.so` file, the directory had a `rejson.dylib`. When I attempted run the loadmodule command, I errored out.

```
$ redis-server /usr/local/etc/redis.conf

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 181
>>> 'loadmodule /Users/sampastoriza/rejson/lib/rejson.dylib'
Bad directive or wrong number of arguments
```
Any thoughts on what might be happening here? Is there another location for the rejson.so file? Thanks!

**Comment by pastorsj** [comment]
It seems that .dylib files are compiled differently that .so files, which might explain the error, but I am not sure how to fix the problem

**Comment by itamarhaber** [comment]
Thanks for reporting - I've yet to put my hands on a Mac to build this... @dvirsky may be able to help.

**Comment by dvirsky** [comment]
I'll have a look. could you try just renaming the file to .so and see if it works?

**Comment by pastorsj** [comment]
I did change it to a .so file and it outputs the same error

**Comment by itamarhaber** [comment]
Update.

Good news: thanks to @dvirsky we refactored the project to use `make` instead of cmake, so build is now successful for Mac OS, yippie.

Less bad news: configuring the CI to support Mac OS is maddening, currently TBD.

More bad news: although the build succeeds on Mac OS, tests are completely borking because something's off with allocating and/or free memory. Need to debug in the native environment - WIP.

**Comment by pastorsj** [comment]
Thanks for the update! @itamarhaber @dvirsky

**Comment by itamarhaber** [comment]
@pastorsj if you have a chance, please pull the latest and try running `make clean; make all; make test` - I have an unsubstantiated feeling that we're getting near.

**Comment by pastorsj** [comment]
```
/Library/Developer/CommandLineTools/usr/bin/make -C ./test all
cc -I"/Users/sampastoriza/Documents/Programming/rejson/test/../src" -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl"  -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o test_object.out test_object.c /Users/sampastoriza/Documents/Programming/rejson/test/../src/librejson.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl/libjsonsl.a -lm
cc -I"/Users/sampastoriza/Documents/Programming/rejson/test/../src" -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl"  -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o test_json_object.out test_json_object.c /Users/sampastoriza/Documents/Programming/rejson/test/../src/librejson.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl/libjsonsl.a -lm
cc -I"/Users/sampastoriza/Documents/Programming/rejson/test/../src" -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl"  -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o json_validator.out json_printer.c /Users/sampastoriza/Documents/Programming/rejson/test/../src/librejson.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl/libjsonsl.a -lm
./test_object.out
.......................................................................................................................................................................................................................

8 tests, 215 assertions, 0 failures

Finished in 0.00013559 seconds (real) 0.00010200 seconds (proc)

./test_json_object.out
............................................................................................................................

17 tests, 124 assertions, 0 failures

Finished in 0.00032449 seconds (real) 0.00025200 seconds (proc)

./test_json_validator.sh

Should PASS: ........................................
Should FAIL: .......................................................................

111 JSON files validated, 0 problems detected
/Library/Developer/CommandLineTools/usr/bin/make -C pytest
python -m unittest discover
E
======================================================================
ERROR: test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 1, in <module>
    from rmtest import ModuleTestCase
ImportError: No module named rmtest


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
make[2]: *** [test] Error 1
make[1]: *** [unittest] Error 2
make: *** [test] Error 2
```
@itamarhaber After pulling the latest changes, I was able to run `make clean` and `make all` without any issues, but `make test` produced the above error. I am running Python 2.7.10. Thoughts?

**Comment by pastorsj** [comment]
I decided to run `pip install rmtest`, which installed that library, but when I ran the tests again, I produced an error indicating that it couldn't load the rejson.so file.

**Comment by pastorsj** [comment]
```
111 JSON files validated, 0 problems detected
/Library/Developer/CommandLineTools/usr/bin/make -C pytest
python -m unittest discover

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "../../src/rejson.so"'
Bad directive or wrong number of arguments
E
...
```

**Comment by pastorsj** [comment]
I looked in the src directory and the rejson.so file does exist

**Comment by pastorsj** [comment]
This is the full stack trace if you are interested,
```
/Library/Developer/CommandLineTools/usr/bin/make -C ./test all
cc -I"/Users/sampastoriza/Documents/Programming/rejson/test/../src" -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl"  -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o test_object.out test_object.c /Users/sampastoriza/Documents/Programming/rejson/test/../src/librejson.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl/libjsonsl.a -lm
cc -I"/Users/sampastoriza/Documents/Programming/rejson/test/../src" -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl"  -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o test_json_object.out test_json_object.c /Users/sampastoriza/Documents/Programming/rejson/test/../src/librejson.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl/libjsonsl.a -lm
cc -I"/Users/sampastoriza/Documents/Programming/rejson/test/../src" -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl"  -I"/Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o json_validator.out json_printer.c /Users/sampastoriza/Documents/Programming/rejson/test/../src/librejson.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/sampastoriza/Documents/Programming/rejson/test/../deps/jsonsl/libjsonsl.a -lm
./test_object.out
.......................................................................................................................................................................................................................

8 tests, 215 assertions, 0 failures

Finished in 0.00013064 seconds (real) 0.00009600 seconds (proc)

./test_json_object.out
............................................................................................................................

17 tests, 124 assertions, 0 failures

Finished in 0.00027277 seconds (real) 0.00020800 seconds (proc)

./test_json_validator.sh

Should PASS: ........................................
Should FAIL: .......................................................................

111 JSON files validated, 0 problems detected
/Library/Developer/CommandLineTools/usr/bin/make -C pytest
python -m unittest discover

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/sampastoriza/Documents/Programming/rejson/test/pytest../../src/rejson.so"'
Bad directive or wrong number of arguments
E
======================================================================
ERROR: testAllJSONCaseFiles (test.ReJSONTestCase)
Test using all JSON test case files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 622, in testAllJSONCaseFiles
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testArrIndexCommand (test.ReJSONTestCase)
Test JSON.ARRINDEX command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 418, in testArrIndexCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testArrPopCommand (test.ReJSONTestCase)
Test JSON.ARRPOP command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 464, in testArrPopCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testArrTrimCommand (test.ReJSONTestCase)
Test JSON.ARRTRIM command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 443, in testArrTrimCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testArrayCRUD (test.ReJSONTestCase)
Test JSON Array CRUDness
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 352, in testArrayCRUD
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testDelCommand (test.ReJSONTestCase)
Test REJSON.DEL command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 261, in testDelCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testGetNonExistantPathsFromBasicDocumentShouldFail (test.ReJSONTestCase)
Test failure of getting non-existing values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 182, in testGetNonExistantPathsFromBasicDocumentShouldFail
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testGetPartsOfValuesDocumentMultiple (test.ReJSONTestCase)
Test correctness of an object returned by JSON.GET
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 216, in testGetPartsOfValuesDocumentMultiple
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testGetPartsOfValuesDocumentOneByOne (test.ReJSONTestCase)
Test type and value returned by JSON.GET
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 202, in testGetPartsOfValuesDocumentOneByOne
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testIssue_13 (test.ReJSONTestCase)
https://github.com/RedisLabsModules/rejson/issues/13
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 668, in testIssue_13
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testLenCommands (test.ReJSONTestCase)
Test the JSON.ARRLEN, JSON.OBJLEN and JSON.STRLEN commands
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 497, in testLenCommands
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testMgetCommand (test.ReJSONTestCase)
Test REJSON.MGET command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 228, in testMgetCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testNumIncrCommand (test.ReJSONTestCase)
Test JSON.NUMINCRBY command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 552, in testNumIncrCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testObjKeysCommand (test.ReJSONTestCase)
Test JSON.OBJKEYS command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 535, in testObjKeysCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testObjectCRUD (test.ReJSONTestCase)
Test JSON Object CRUDness
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 297, in testObjectCRUD
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testRespCommand (test.ReJSONTestCase)
Test JSON.RESP command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 591, in testRespCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testSetBehaviorModifyingSubcommands (test.ReJSONTestCase)
Test JSON.SET's NX and XX subcommands
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 157, in testSetBehaviorModifyingSubcommands
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testSetGetComparePassJSONCaseFiles (test.ReJSONTestCase)
Test setting, getting, saving and loading passable JSON test case files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 641, in testSetGetComparePassJSONCaseFiles
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testSetGetWholeBasicDocumentShouldBeEqual (test.ReJSONTestCase)
Test basic JSON.GET/JSON.SET
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 144, in testSetGetWholeBasicDocumentShouldBeEqual
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testSetInvalidPathShouldFail (test.ReJSONTestCase)
Test that invalid paths fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 93, in testSetInvalidPathShouldFail
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testSetReplaceRootShouldSucceed (test.ReJSONTestCase)
Test replacing the root of an existing key with a valid object succeeds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 127, in testSetReplaceRootShouldSucceed
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testSetRootWithInvalidJSONValuesShouldFail (test.ReJSONTestCase)
Test that setting the root of a ReJSON key with invalid JSON values fails
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 81, in testSetRootWithInvalidJSONValuesShouldFail
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testSetRootWithJSONValuesShouldSucceed (test.ReJSONTestCase)
Test that the root of a JSON key can be set with any valid JSON
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 107, in testSetRootWithJSONValuesShouldSucceed
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testStrCommands (test.ReJSONTestCase)
Test JSON.STRAPPEND and JSON.STRLEN commands
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 578, in testStrCommands
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

======================================================================
ERROR: testTypeCommand (test.ReJSONTestCase)
Test JSON.TYPE command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sampastoriza/Documents/Programming/rejson/test/pytest/test.py", line 484, in testTypeCommand
    with self.redis() as r:
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 95, in __enter__
    self._startProcess()
  File "/Library/Python/2.7/site-packages/rmtest/disposableredis/__init__.py", line 78, in _startProcess
    .format(self.process.returncode, self.process.stdout.read()))
RuntimeError: Process has exited with code 1
. Redis output:

----------------------------------------------------------------------
Ran 25 tests in 2.775s

FAILED (errors=25)
make[2]: *** [test] Error 1
make[1]: *** [unittest] Error 2
make: *** [test] Error 2
```

**Comment by itamarhaber** [comment]
I'm grateful - thanks.

1. to run the module's unit test you should `pip install redis rmtest` before (documented in doc/developer.md)
2. something needs to be fixed with how the unittest finds the module, will do that.
3. it may be that on mac the suffix for the lib isn't `so` but `dyn` or `dynlib` or something?

What that test tries doing is creating a disposable Redis server. You skip that and can run the tests against a Redis server that you've loaded (with the module, assuming we find the lib in 3) - cd to rejson/test/pytest and run `REDIS_PORT=6379 make` to have the tests run against the instance listening at that port.

**Comment by dvirsky** [comment]
@pastorsj looks like your tests are running against an older version of redis which doesn't support modules. As @itamarhaber mentioned, the tests actually create epehmeral redis child processes. So either direct the tests at an existing redis with the module loaded, or tell the tests where to find redis 4.0 by specifying the env var `REDIS_PATH=/path/to/redis-server`

**Comment by pastorsj** [comment]
@dvirsky I am running the stable version of Redis v3.2.8. I assume I need to update to Redis 4.0?

**Comment by dvirsky** [comment]
@pastorsj yes, install redis 4.0 RC3 or unstable please. 3.2 does not support modules at all.

**Comment by itamarhaber** [comment]
@dvirsky O(rz)

**Comment by pastorsj** [comment]
@dvirsky I installed redis 4.0 RC3, was able to load the module and start using the command `./redis-server --loadmodule ../../Programming/rejson/src/rejson.so`, but the tests still fail when I run `REDIS_PORT=6379 make` with the same error messages.

**Comment by dvirsky** [comment]
you should run make test IIRC, not just make

**Comment by pastorsj** [comment]
I thought that I could run `REDIS_PORT=6379 make` @itamarhaber mentioned that above. I will rerun the tests.

**Comment by pastorsj** [comment]
When I run REDIS_PORT=6379 make test` from the root directory, I receive the same errors. I was running `REDIS_PORT=6379 make` in the test directory, which should have the same effects.

**Comment by dvirsky** [comment]
just install redis 4.0. @itamarhaber all tests pass on my mac, and no compilation errors.

**Comment by itamarhaber** [comment]
@dvirsky ty

@pastorsj sorry for any confusion. There are two options for running the tests, both require having at least a v4 (or grater) `redis-server` executable.

Method A - disposable Redis: you just call `make  test` from the root. Assuming that `redis-server` is in the path, that should be all. If it isn't, you can provide the location with the `REDIS_PATH` env var.

Method B - independent Redis: start `redis-server` AND load the module. Then go and `make test` with the `REDIS_PORT=<port>` env var to direct the test to it.

Hope this helps!

**Comment by pastorsj** [comment]
@itamarhaber Right, I understood that, but the tests still fail. I am running the independent version since `redis-server` on the path is connected to the stable version (3.8.2). I am able to load the module using redis 4.0, but when running the command on my mac, the tests fail. Let me take a look to see if I can figure out what is going wrong.

**Comment by pastorsj** [comment]
@itamarhaber @dvirsky I redownloaded `redis 4.0 rc3` from github, ran `make` and then ran `./src/redis-server`. The version seems to be `Redis 3.9.103 (00000000/0) 64 bit` when I view the output after starting redis. Is that an issue? Should it be `Redis 4.0`

**Comment by itamarhaber** [comment]
No, that's what it says for the release candidate so that's ok. Alternatively, you can use the `unstable` branch from the Redis repo.

Related: is there any Mac OS brew needed to make the project? I want to add whatever's missing to the docs.

**Comment by pastorsj** [comment]
@itamarhaber There are no brew installations required to make the project. I installed the stable version of Redis though brew initially, nothing else.

**Comment by slashetc** [comment]
```
make -C ./test/ all
make: Entering directory '/home/user1/rejson/test'
cc -I"/home/user1/rejson/test/../src" -I"/home/user1/rejson/test/../deps/jsonsl"  -I"/home/user1/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -o test_object.out test_object.c /home/user1/rejson/test/../src/librejson.a /home/user1/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /home/user1/rejson/test/../deps/jsonsl/libjsonsl.a -lm -lrt 
cc -I"/home/user1/rejson/test/../src" -I"/home/user1/rejson/test/../deps/jsonsl"  -I"/home/user1/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -o test_json_object.out test_json_object.c /home/user1/rejson/test/../src/librejson.a /home/user1/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /home/user1/rejson/test/../deps/jsonsl/libjsonsl.a -lm -lrt
cc -I"/home/user1/rejson/test/../src" -I"/home/user1/rejson/test/../deps/jsonsl"  -I"/home/user1/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -o json_validator.out json_printer.c /home/user1/rejson/test/../src/librejson.a /home/user1/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /home/user1/rejson/test/../deps/jsonsl/libjsonsl.a -lm -lrt
./test_object.out
.......................................................................................................................................................................................................................

8 tests, 215 assertions, 0 failures

Finished in 0.00013925 seconds (real) 0.00009384 seconds (proc)

./test_json_object.out
............................................................................................................................

17 tests, 124 assertions, 0 failures

Finished in 0.00023462 seconds (real) 0.00018749 seconds (proc)

./test_json_validator.sh

Should PASS: ........................................
Should FAIL: .......................................................................

111 JSON files validated, 0 problems detected
make -C pytest
make[1]: Entering directory '/home/user1/rejson/test/pytest'
python -m unittest discover
.........................
----------------------------------------------------------------------
Ran 25 tests in 2.840s

OK
make[1]: Leaving directory '/home/user1/rejson/test/pytest'
make: Leaving directory '/home/user1/rejson/test'
```
I've added `loadmodule /var/lib/redis/rejson.so` at the end of /etc/redis/redis.conf

```
sudo systemctl status redis-server.service
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled)
   Active: failed (Result: start-limit) since Fri 2017-06-16 17:09:54 UTC; 1s ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 16059 ExecStopPost=/bin/run-parts --verbose /etc/redis/redis-server.post-down.d (code=exited, status=0/SUCCESS)
  Process: 16055 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 16052 ExecStop=/bin/run-parts --verbose /etc/redis/redis-server.pre-down.d (code=exited, status=0/SUCCESS)
  Process: 10761 ExecStartPost=/bin/run-parts --verbose /etc/redis/redis-server.post-up.d (code=exited, status=0/SUCCESS)
  Process: 16185 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=1/FAILURE)
  Process: 16182 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exited, status=0/SUCCESS)
 Main PID: 10760 (code=exited, status=0/SUCCESS)

Jun 16 17:09:54 ip-10-130-130-152 systemd[1]: Failed to start Advanced key-value store.
Jun 16 17:09:54 ip-10-130-130-152 systemd[1]: Unit redis-server.service entered failed state.
Jun 16 17:09:54 ip-10-130-130-152 systemd[1]: redis-server.service start request repeated too quickly, refusing to start.
Jun 16 17:09:54 ip-10-130-130-152 systemd[1]: Failed to start Advanced key-value store.
Jun 16 17:09:54 ip-10-130-130-152 systemd[1]: Unit redis-server.service entered failed state.
```

I've try to move the module to /etc/redis/rejson.so and then replace loadmodule path in conf.

```
sudo /usr/bin/redis-server /etc/redis/redis.conf

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1052
>>> 'loadmodule /etc/redis/rejson.so'
Bad directive or wrong number of arguments
```

But finally, it work when start like this

```
sudo redis-server --loadmodule /etc/redis/rejson.so
16254:C 16 Jun 17:14:18.371 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
16254:C 16 Jun 17:14:18.371 # Redis version=3.9.103, bits=64, commit=00000000, modified=0, pid=16254, just started
16254:C 16 Jun 17:14:18.371 # Configuration loaded
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.9.103 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 16254
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

16254:M 16 Jun 17:14:18.372 # Server initialized
16254:M 16 Jun 17:14:18.372 # <ReJSON> JSON data type for Redis v999.999.999 [encver 0]
16254:M 16 Jun 17:14:18.372 * Module 'ReJSON' loaded from /etc/redis/rejson.so
16254:M 16 Jun 17:14:18.372 * Ready to accept connections
```

**Comment by dvirsky** [comment]
@slashetc `*** FATAL CONFIG FILE ERROR ***` means you are loading a module into an older version of redis of course. I would dig into where systemd is trying to run redis from, I'm willing to be that you have 4.0 installed in `/usr/local/bin` and 3.2 or older installed in `/usr/bin` or something like that.

**Comment by slashetc** [comment]
@dvirsky Thanks ! Sorry that was obvious

**Comment by mnunberg** [comment]
Seems this is resolved for now? closing this issue.

**Comment by tilmanotto** [comment]
Unfortunately the problem still exists with Redis 4.0.9 standalone and rejson. Works only with --loadmodule parameter in command line, not in redis.conf (Linux Mint 18.3).

**Comment by dh3wr** [comment]
+1

**Comment by itamarhaber** [comment]
@tilmanotto @dh3wr please open a new issue and include the relevant info
